backend:
  name: github
  repo: MitchellXOTWOD/Elembecreations
  branch: main
  base_url: https://elembecreations.slimmitch-mn.workers.dev/

media_folder: "assets/images/gallery" # Where uploaded images will save in your project
public_folder: "/assets/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery Images"
    folder: "data/gallery" # The CMS will save a small file for each image here
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Gallery Image", name: "image", widget: "image" }
      - { label: "Date Added", name: "date", widget: "datetime" }